config/routes.rb
Rails.application.routes.draw do
  root 'conversations#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :private_messages, only: [:create]
  resources :conversations, only: [:index, :show, :new]

# config.action_cable.mount_path = "/cable #might need this?
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  has_many :private_messages, -> { order(created_at: :asc) }, dependent: :destroy
  validates :author, uniqueness: {scope: :recipient}

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.recipient_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    where(author_id: sender_id, recipient_id: recipient_id).or(where(author_id: recipient_id, recipient_id: sender_id))
end

  def with(current_user)
    author == current_user ? recipient : author
  end

  def participates?(user)
    author == user || recipient == user
  end

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates :body, presence: true

  after_commit { MessageRelayJob.perform_now(self) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'recipient_id'
  has_many :private_messages, dependent: :destroy
  before_save {email.downcase!}
  has_secure_password
  validates :email,
   presence: true,
   uniqueness: {case_sensitive: false}

   def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #maybe enforce logged in state heres
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    if (helpers.logged_in?)
      @conversations = Conversation.participating(helpers.current_user).order('updated_at DESC')
      redirect_to users_path if @conversations.empty?
    else
      redirect_to login_path
    end
  end

  def show
    @conversation = Conversation.find_by(id: params[:id])
    redirect_to root_path unless @conversation && @conversation.participates?(helpers.current_user)
  end
  
  def new
    if @recipient = User.find_by(id: params[:recipient_id])
      @conversation = Conversation.between(helpers.current_user.id, @recipient.id)[0] ||
      Conversation.create(author_id: helpers.current_user.id, recipient_id: @recipient.id)
      redirect_to conversation_path(@conversation)
    else
      flash[:error] = "Recipient does not exist"
      redirect_to root_path
    end
  end

  def create
  end

  def destroy
  end
end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
  before_action :find_conversation!

  def create
    @conversation
    @private_message = helpers.current_user.private_messages.build(private_message_params)
    @private_message.conversation_id = @conversation.id
    unless @private_message.save!
      flash[:error] = "Something went wrong, try again"
    end
  end

  private

  def private_message_params
    params.require(:private_message).permit(:body)
  end

  def find_conversation!
      @conversation = Conversation.find_by(id: params[:conversation_id])
      flash[:error] = 'no conversation'
      redirect_to(root_path) and return unless @conversation && @conversation.participates?(helpers.current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    is_guest_login = params[:session][:guest]
    if is_guest_login
      create_and_log_in_as_guest
    else
      user = User.find_by(email: params[:session][:email].downcase)
            .try(:authenticate, params[:session][:password]) #maybe we can move this into an auth module, since logging in is always paired with authentication or account creation.
      if user
        helpers.log_in(user)
        redirect_to root_path
      else
        flash.now[:notice] = "Login information is incorrect"
        render 'new'
      end
    end
  end

  def destroy
    helpers.log_out
    redirect_to root_url
  end

  private

  def create_and_log_in_as_guest
    random_string = SecureRandom.hex(10)
    guest_user = User.new(email: "guest-#{random_string}@temp.com", password: random_string)
    
    if guest_user.save
      helpers.log_in(guest_user)
      redirect_to root_path
    else
      flash.now[:error] = "Problem creating guest user"
      render 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    if helpers.logged_in?
      render 'show'
    else
      redirect_to login_url
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      helpers.log_in(@user)
      redirect_to users_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/private_messages_helper.rb
module PrivateMessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(authenticated_user)
    cookies.signed[:user_id] ||= authenticated_user.id
    @current_user = authenticated_user
  end

  def is_current_user?(user)
    user.id == current_user.id
  end

  def current_user
    if cookies.signed[:user_id]
      @current_user ||= User.find_by(id: cookies.signed[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def ensure_logged_in
    unless logged_in?
      redirect_to(login_path)
    end    
  end

  def log_out
    cookies.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversation.html.erb
<div>
  Chatting with <%= conversation.with(current_user).name %>
  <br>
  <em><%= conversation.private_messages.present? ? conversation.private_messages.last.body.truncate(50) + '...' : 'No messages yet' %></em>
  <br>
  <%= link_to 'View conversation', conversation_path(conversation) %>
  <hr>
</div>

app/views/conversations/_new.html.erb
<%= form_with(model: PrivateMessage.new, id: 'js-send-form') do |f| %>
  <%= hidden_field_tag 'conversation_id', @conversation.id %>
  <div class='form-group input-group'>
    <%= f.text_area :body, class: 'form-control', rows: '1' %>
    <div class="input-group-append">
      <%= f.submit 'send', class: 'form-control btn btn-primary btn-sm' %>
    </div>
  </div>
<% end %>

app/views/conversations/index.html.erb
<h1>Your conversations</h1>

<div id="conversations">
  <%= render @conversations %>
</div>

app/views/conversations/show.html.erb
<h3>Chatting with <%= @conversation.with(current_user).name %></h3>

<div id="conversation-main">
  <div id="conversation-body">
    <%= render @conversation.private_messages %>
  </div>
  <%= render "conversations/new" %>
  </div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class='alert alert-info'>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<nav class='nav bg-light justify-content-end'>
  <%= link_to 'Home', root_path, class: ["nav-link", 'nav-item', 'active'] %>
  <%= link_to 'Users', users_path, class: ["nav-link", 'nav-item']%>
  <% if logged_in? %>
  <p class='nav-item nav-link'>
    Hello, <%= current_user.name.capitalize %>! | 
    <span hidden id='uid-ref' data-uid=<%=current_user.id%>></span>
    <%= link_to 'log out', logout_path, method: :delete %>
  </p>
<% else %>
  <%= link_to 'log in', login_path, class: ["nav-link", 'nav-item'] %>
<% end %>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RChat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= action_cable_meta_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash'%>
      <%= render 'layouts/menu'%>

      <%= yield %>
    </div>

  </body>
</html>

app/views/private_messages/_private_message.html.erb
<div class="private_message" data-uid=<%=private_message.user.id%>>
  <p class='show-message-body'><%= private_message.body %></p>
  <p class='show-message-info'>
    <strong>
      <%= time_ago_in_words private_message.created_at %>
    </strong> ago
    <br>
  </p>
</div>

app/views/private_messages/create.js.erb
const messages = document.querySelector('#conversation-body');
// messages.insertAdjacentHTML('beforeend', '<%=j render @private_message %>');

app/views/private_messages/new.html.erb
<h1>New message for <%= @recipient.name %></h1>
<%= form_for @private_message, remote: true do |f| %>
  <%= hidden_field_tag 'recipient_id', @recipient.id %>
  <div class='form-group input-group'>
    <%= f.text_area :body, class: 'form-control', rows: '1' %>
    <div class="input-group-append">
      <%= f.submit "Send Message!", class: 'form-control btn-sm btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
 
    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for(user) do |f| %>
  <div class='form-group'>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control'%>
  </div>

  <div class='form-group'>
    <%= f.submit 'Sign up!', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= user.name %> | <%= link_to (user == current_user ? 'Talk to yourself?' :  "Start a conversation"), new_conversation_path(recipient_id: user.id) %>
</li>

app/views/users/index.html.erb
<h1>All the users</h1>
<ul><%= render @users %></ul>

app/views/users/new.html.erb
<h1>Sign up for an account</h1>
<%= render 'form', user: @user %>
<div>
  <p>Returning user? <%= link_to 'login here', "/login" %> </p>
</div>

app/views/users/show.html.erb
<h1>User page</h1>
  <%= link_to "log out", logout_path, method: :delete %>
  <%= "You are logged in as " + current_user.email %>